# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!
platform :ios, '10.0'

target 'Pros' do
  use_frameworks!

  pod 'SwiftyJSON'

  def test_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'ProsTests' do
    inherit! :search_paths
    test_pods
  end

  target 'ProsUITests' do
    inherit! :search_paths
    test_pods
  end

end
